# Spotify Data Set

In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('spotify_dataset.csv')
df.head()

/var/folders/p9/9vqlyg213v3b9h9zrksgz6z00000gn/T/ipykernel_55081/1997009161.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('spotify_dataset.csv')

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.461,1,-6.746,0,0.143,0.0322,0.000001,0.358,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.42,0.166,1,-17.235,1,0.0763,0.924,0.000006,0.101,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.359,0,-9.734,1,0.0557,0.21,0.0,0.117,0.12,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.905,0.000071,0.132,0.143,181.74,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.443,2,-9.681,1,0.0526,0.469,0.0,0.0829,0.167,119.949,4,acoustic

In [5]:
df['artists'].value_counts()

artists
The Beatles                 558
George Jones                542
Stevie Wonder               472
Linkin Park                 448
Ella Fitzgerald             444
                           ...
Bira Santos                   2
GeoM;Dimitris Athanasiou      2
Novo Som;L??via Gavazzi       2
Moya Mishel;LSP               1
artists                       1
Name: count, Length: 30634, dtype: int64

In [9]:
ts_songs=df.query("artists=='Taylor Swift'")
ts_songs['album_name'].value_counts()

album_name
Autumn Vibes 2022                               8
Sunny Mornings                                  2
1989 (Deluxe)                                   2
folklore                                        2
1989                                            2
reputation                                      2
Fearless (Big Machine Radio Release Special)    2
Lover                                           2
Name: count, dtype: int64

In [17]:
D1_songs=df.query("artists=='One Direction'")
D1_songs.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
77256,5O2P9iiztwhomNh8xkR9lJ,One Direction,FOUR (Deluxe),Night Changes,88,226600,False,0.672,0.52,8,-7.747,1,0.0353,0.859,0.0,0.115,0.37,120.001,4,pop
77462,4cluDES4hQEUhmXj6TXkSo,One Direction,Up All Night,What Makes You Beautiful,84,199986,False,0.726,0.787,4,-2.494,1,0.0737,0.009,0.0,0.0596,0.888,124.99,4,pop
77607,2Bs4jQEGMycglOfWPBqrVG,One Direction,FOUR (Deluxe),Steal My Girl,80,228133,False,0.536,0.768,10,-5.948,0,0.0347,0.00433,0.0,0.114,0.545,77.217,4,pop
78054,2K87XMYnUMqLcX3zvtAF4G,One Direction,Made In The A.M. (Deluxe Edition),Drag Me Down,80,192120,False,0.73,0.703,0,-5.672,0,0.0369,0.109,0.0,0.0657,0.595,138.113,4,pop
78167,4nVBt6MZDDP6tRVdQTgxJg,One Direction,Midnight Memories (Deluxe),Story of My Life,83,245493,False,0.6,0.663,3,-5.802,1,0.0477,0.225,0.0,0.119,0.286,121.07,4,pop